version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - helpdesk


  service-discovery:
    image: aaanm13/helpdesk-service-discover:1.0.0
    container_name: 'service-discover'
    environment:
      - PORT=8761
    ports:
      - "8761:8761"
    expose:
      - 8761
    networks:
      - helpdesk
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  config-server:
    image: aaanm13/helpdesk-config-server:1.0.0
    container_name: 'config-server'
    environment:
      - CONFIG_SERVER_URI=http://github.com/aaanm1309-1/helpdesk20-config
      - CONFIG_SERVER_USERNAME=aaanm1309-1
      - CONFIG_SERVER_PASSWORD=
      - PORT=8888
    ports:
      - "8888:8888"
    expose:
      - 8888
    networks:
      - helpdesk
    depends_on:
      - service-discovery
    links:
      - service-discovery



  api-gateway:
    image: aaanm13/helpdesk-api-gateway:1.0.0
    container_name: 'api-gateway'
    environment:
      - CONFIG_SERVER_URI=config-server:8888
      - PORT=8765
    ports:
      - "8765:8765"
    expose:
      - 8765
    networks:
      - helpdesk
    depends_on:
      - config-server
      - service-discovery
    links:
      - config-server
      - service-discovery

networks:
  helpdesk:
    driver: bridge