spring:
  profiles:
    active: dev
  application:
    name: 'user-service-api'
eureka:
  instance:
    prefer-ip-address: true
  cloud:
    config:
      uri: 'config-server'
#      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
