spring:
  profiles:
    active: dev
  application:
    name: 'service-discover'
  cloud:
    config:
      uri: 'config-server'
#      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: ${PORT:8761}
