spring:
  profiles:
    active: dev
  application:
    name: 'helpdesk-bff'
  cloud:
    config:
      uri: 'config-server'
#      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: ${PORT:8081}