spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${CONFIG_SERVER_URI:http://github.com/aaanm1309-1/helpdesk20-config}
          username: ${CONFIG_SERVER_USERNAME}
          password: ${CONFIG_SERVER_PASSWORD}
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: ${SERVER_PORT:8888}
